CREATE USER inventory IDENTIFIED BY "1011SQLexp";

GRANT CONNECT, RESOURCE, dba TO inventory;

GRANT UNLIMITED TABLESPACE TO inventory;

ALTER PROFILE DEFAULT LIMIT password_reuse_time UNLIMITED;

ALTER PROFILE DEFAULT LIMIT password_life_time UNLIMITED;